kern: Nix mutex_owner.
There is no valid reason to use this except in assertions of the form

	KASSERT(mutex_owner(lock) == curlwp),

which is more obviously spelled as

	KASSERT(mutex_owned(lock)).

Exception: There's one horrible kludge in zfs that abuses this, which
should be eliminated.

XXX kernel revbump -- deleting symbol

PR kern/47114